name: Django CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: 11.5
        postgresql db: event
        postgresql user: unicore
        postgresql password: quatro-test 
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        export ${{ secrets.JWT_SECRET }}
    - name: Run Tests
      run: |
       # python manage.py test
        python manage.py migrate
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: mr-smithers-excellent/docker-build-push@v4
      name: Build & push Docker image
      with:
        image: sedjro/quatroApi
        tag: latest
        registry: docker.io
        dockerfile: /home/runner/work/ops-hiring-test/ops-hiring-test/Dockerfile
        username:  ${{ secrets.DOCKER_LOGIN }} 
        password: ${{ secrets.DOCKER_ACCES_TOKEN }}
